### PR TITLE
Add max_concurrent_trials parameter to Tune Executor

### PR DESCRIPTION
**Pull request by arnavgarg1**
Add `max_concurrent_trials` to the Ludwig docs for hyperopt executor.

### CODE REVIEW

**Comment by justinxzhao** [comment]
This is a new parameter for 0.6 only?

**Comment by arnavgarg1** [comment]
> 

Nope, I think it's existed even for 0.5 but for some reason we never documented this. I think it's an important thing to document so that users can control how many trials actually run in parallel incase they don't want to use up all of their resources.

**Comment by justinxzhao** [comment]
@arnavgarg1 in that case, should we merge to master?

**Comment by arnavgarg1** [comment]
@justinxzhao Yup, happy to merge to master 👍 The plan is to eventually merge `0.6` into master as well right?

**Pull request merged**
