### PR TITLE
Reorder features to be alphabetic for faster lookup

### PR DESCRIPTION
**Pull request by arnavgarg1**
Reorders feature types in alphabetic order in user config so that it's easier to search for what you're looking for

### CODE REVIEW

**Comment by arnavgarg1** [comment]
@justinxzhao IMO, we should do this for all the encoder/decoder parameters in the documentation as well (wherever there are keyword arguments). If you think this makes sense, I'm happy to create a task for it and work on it before the v0.6 release.

**Comment by justinxzhao** [comment]
> @justinxzhao IMO, we should do this for all the encoder/decoder parameters in the documentation as well (wherever there are keyword arguments). If you think this makes sense, I'm happy to create a task for it and work on it before the v0.6 release.

I don't think the alphabetization of encoder/decoder parameters is crucial, but parameter order is. There's a larger FR to generate Ludwig docs automatically from module schemas. Perhaps this is something to defer until that work has been scheduled.

My intention behind the original ordering of features in the side panel was to 1) surface the most commonly used feature types first, and 2) separately group input-only and input-and-output feature types. That said, I also see the merits of a simple, alphabetical list.

CC @w4nderlust in case he has any thoughts.

**Comment by w4nderlust** [comment]
For the parameters, there is a logic of being gradual from input to output in many cases. for isntance for parallel cnn, first the embedding parametrs, then the conv parameters and then the fc parameters.

**Comment by arnavgarg1** [comment]
@w4nderlust @justinxzhao that makes sense! I've just found that on many other docs (Keras, PyTorch), in many scenarios, things are ordered alphabetically where it makes sense. I agree that the most important parameters should go on top, but maybe after that it does make sense to maybe keep things alphabetical. We can still group them by embedding_parameters, conv_parameters and fc_parameters, but within each of those groups, it might help to have them alphabetically. 

The other train of thought is to just leave this as is for now because of the FR to generate the docs automatically, and also because no users have really complained about it. I'll close this for now.

**Pull request closed without merging**
