### PR TITLE
Updated backend docs

### PR DESCRIPTION
**Pull request by tgaddair**

### CODE REVIEW

**Review by dantreiman — APPROVED** [review]
LGTM

**Comment by tgaddair** [comment]
@justinxzhao do you know why this test is failing?

**Comment by justinxzhao** [comment]
> @justinxzhao do you know why this test is failing?

Yes. It looks like there's a small diff in the auto-generated docs from the latest 0.5.2 release. 

https://github.com/ludwig-ai/ludwig-docs/pull/160

I'll also put together a change to add this to the release process.

**Comment by justinxzhao** [comment]
I believe if you rebase the checks should pass now.

**Review by justinxzhao — APPROVED** [review]

**Pull request merged**
