### PR TITLE
[MAINTENANCE] Various typographical error fixes and improvements in the English usage

### PR DESCRIPTION
**Pull request by alexsherstinsky**
### Scope
* This change proposes to fix some typos and improve the readability of the Ludwig documentation.
* More similar pull requests are to come gradually.

### CODE REVIEW

**Review by arnavgarg1 — APPROVED** [review]
LGTM! Although, I wonder if we should move `contributing.md` from main ludwig to ludwig docs, and then point to the ludwig docs contributing.md from the main ludwig repo. What do you think?

**Comment by alexsherstinsky** [comment]
> LGTM! Although, I wonder if we should move `contributing.md` from main ludwig to ludwig docs, and then point to the ludwig docs contributing.md from the main ludwig repo. What do you think?

@arnavgarg1 Before I merge, let us discuss.  I kept it in the code repository using the logic that contributing is closer to code than documentation.  I am not sure which is the best way; what is the reason for your recommendation that it be kept in the documentation repository?  Thanks.

**Comment by arnavgarg1** [comment]
Btw, you will also need to edit mkdocs.yaml to remove the contributing guide from the website index (it'll make sense once you take a look at the website)!

**Comment by arnavgarg1** [comment]
@alexsherstinsky got it! I think that's reasonable actually, we can leave it in the main Ludwig repo.

**Comment by alexsherstinsky** [comment]
> Btw, you will also need to edit `mkdocs.yaml` to remove the contributing guide from the website index (it'll make sense once you take a look at the file in the repo)!

@arnavgarg1 I thought that I did that -- could you please double check to make sure I did not miss it?  Thanks!

**Comment by arnavgarg1** [comment]
Oh I see it now, sorry about that!

**Comment by alexsherstinsky** [comment]
> Oh I see it now, sorry about that!

@arnavgarg1 Not at all -- really appreciate doing the rechecking.  Is there a way to view the "staged" content of the pull request, before I merge?  Something like Netlify perhaps?  Thanks!

**Pull request merged**
