### PR TITLE
[BUGFIX] Provide Documentation for Importing Visualization Modules.

### PR DESCRIPTION
**Pull request by alexsherstinsky**
### Scope
This change provides the appropriate solution to the Issue [Unable to create visualizations using Python API](https://github.com/ludwig-ai/ludwig/issues/3922), which was reported in the Ludwig repository.  The appropriate solution is to provide the documentation on how to import the relevant modules.  This is a cleaner approach than adding imports into the top-level `__init__.py` in the Ludwig codebase.  The solution augments the automatic documentation mechanism by enabling it to include module-level docstrings.  /cc @w4nderlust @sanjaydasgupta

### CODE REVIEW

**Comment by alexsherstinsky** [comment]
@arnavgarg1 Good point -- this is what it looks like with the changes.  Thank you.
Screenshot 2024-02-17 at 01 00 22

**Comment by arnavgarg1** [comment]
Is it worth adding a comment that if the from Ludwig import visualise fails/errors, to pip install "ludwig[viz]"?

**Comment by alexsherstinsky** [comment]
> Is it worth adding a comment that if the from Ludwig import visualise fails/errors, to pip install "ludwig[viz]"?

@arnavgarg1 In my opinion it is not necessary, because if the code fails, there is already an error message in `ludwig/utils/visualization_utils.py` that will say that this is needed.  What do you think?  Thanks!

**Comment by arnavgarg1** [comment]
Okay great!

**Review by arnavgarg1 — APPROVED** [review]

**Pull request merged**
