### PR TITLE
0.6: Merge in changes from master.

### PR DESCRIPTION
**Pull request by justinxzhao**

### CODE REVIEW

**Comment by arnavgarg1** [comment]
@justinxzhao Would the best way to review this is to just pull this branch in locally and then launch it locally so I can take a look?

**Comment by justinxzhao** [comment]
@arnavgarg1 checking out the branch locally with something like

```
brew install hub
hub pr checkout 215
```

https://github.com/github/hub

And then spinning up a local instance totally works.

These changes should be relatively safe though, as the only major merge conflict was on the mkdocs.yaml file, and I've retained the new docs we added for defaults and model types.

**Comment by arnavgarg1** [comment]
This change looks good to me! 

Do you know if there's a way to indent some of these nested subsections, for e.g., each of the feature types in features? 

Screen Shot 2022-09-19 at 5 12 51 PM

**Comment by arnavgarg1** [comment]
For `Community` and `FAQ`, should we re-structure so that we bring the table of contents to the left side just like we have it for all of the other navbar sections? 

Screen Shot 2022-09-19 at 5 16 06 PM

**Review by arnavgarg1 — APPROVED** [review]

**Comment by justinxzhao** [comment]
@arnavgarg1 These should be fixed now with the latest commit.

**Pull request merged**
